### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by dabstar** [HBDK/ElOverBlik-helper#1]
Great initiative with the eloverblik helper! 

I got it all setup and data is flowing into my InfluxDB, however there is some misalignment between the timestamp and the time interval from eloverblik. I'm assuming that it is a UTC -> DK Summertime issue. 

![image](https://user-images.githubusercontent.com/3286993/86106813-570ac700-bac1-11ea-8fb1-6f53b5812f14.png)

**Comment by HBDK** [comment]
Cool to see that it's running somewhere else. 

But yeah this won't do. i have just made a minor tweak and it looks like it does the trick.
i had the same issue when i tested locally and it looks like it is fixed now, but let's wait with closing this until we know that it works as expected in "production".

**Comment by dabstar** [comment]
Thanks for the swift update! It looks much better now!
