### ISSUE TITLE
values stored as strings

### ISSUE THREAD

**Issue by dabstar** [HBDK/ElOverBlik-helper#5]
It seems the energy consumption values are stored as strings in InfluxDB - it prevents an easy Grafana view of aggregated daily consumption (without looking into Grafana inline conversion options).

Suggest the consumption values are stored as floats in InfluxDB

Thanks again for creating this great helper tool!

**Comment by HBDK** [comment]
Hmm it looks like Changing this will cause a problem with the existing data in the database.
but i guess since all data is available at EloverBlik as well this probably isn't a big issue, i was planning on making something to import old data any ways.

**Comment by HBDK** [comment]
i have made the change and installed it on my own system so now i'm eager to see what actually happens tomorrow morning when it ingests data again.

**Comment by HBDK** [comment]
This mornings run resulted in this:
```
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    Einf.Client.write_points(data)
  File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 594, in write_points
    return self._write_points(points=points,
  File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 672, in _write_points
    self.write(
  File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 404, in write
    self.request(
  File "/usr/local/lib/python3.8/site-packages/influxdb/client.py", line 369, in request
    raise InfluxDBClientError(err_msg, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: field type conflict: input field \"value\" on measurement \"Energy\" is type float, already exists as type string dropped=24"}
```
  
But otherwise everything looks fine..
I think I should add something to catch exceptions from the client and a sort of catch all to ensure that errors are reported if webhooks are enabled.  
But otherwise I think this done feel free to close this issue if you agree.

**Comment by HBDK** [comment]
Ok i was a bit to fast there, it didn't insert data like i expected.

i have a dropped the series and insert all data again using a bulk loader that is in the app folder now.

**Comment by dabstar** [comment]
Thanks for the fix! Works great! The bulkuploader is a super addition!
